# Lez 8 -14/10/21

# Error handling

Sorge il problema di come gestire una failure del codice (non un bug).

Normalmente, in linux, una failure del codice ritorna 0 oppure può ritornare diversi numeri a seconda dell'errore. Questo metodo per segnalare errori nel codice viene chiamato **Error Flag**.

Questo metodo di gestione degli errori ha dei problemi:

- Nel caso la funzione normalmente dovrebbe ritornare un int è ambiguo capire se sia ritorni un output o un error flag
- Bisogna consultare la documentazione ogni volta che si presenta un error flag
- Se il caller di una funzione non controlla gli error flag gli errori si possono propagare nel codice in maniera stealth

Idealmente voglio qualcosa che non sia ambiguo, di facile lettura e che non passi in sordina

## Eccezioni

Un eccezione è un oggetto che può essere chiamato ( **raise** ). Quando si solleva un' eccezione il flusso del codice si interrompe a meno che l'eccezione non viene gestita.

Ogni tipo di errore diverso corrisponde a un messaggio di errore specifico

Per gestire un eccessione è possibile usare un blocco di codice try-except:

```python
try:
    #do something
    #ExceptionType deve essere una classe che eredita dalla classe principale Exception (vedi documentazione)
except ExceptionType:
    #do other things
    #E' possibile inserire un qualsiasi numero di except
    #E' possibile anche fare except eccezione as var_name
```

Sono presenti due ulteriori istruzioni opzionali per la gestione dell'errore da inserire dopo l'except:

- **else**: Viene eseguito solo se nel try block non viene sollevata alcuna eccezione
- **finally**: Viene eseguito sempre, in ogni caso (utile per esempio per chiudere un file). NB. Viene eseguito anche se si trova dopo un return. Viene eseguito SEMPRE

La gestione delle eccezioni può essere molto utile anche per il debug.

**N.B.**: NON usare mai Exception o ancora peggio BaseException negli except perchè questo fa passare errori come NameError, IndexError, ValueError, etc. che sono errori che vogliamo vedere nel caso abbiamo commesso errori nel codice. Inoltre usare BaseException implica non poter usare più Ctrl+C per bloccare l'esecuzione in quanto si è raccolto nell'except anche il keyboard interrrupt

E' sempre meglio usare try-except invece che usare la *programmazione difensiva*, ovvero fare una serie di check con degli if-else per scongiurare che avvenga un errore. Usare if-else può essere problematico soprattutto in caso di programmazione parallela o concorrente in quanto if ed else avvengono in sequenza e nel frattempo lo stato di verità della condizione può cambiare. Invece nel try-except avviene un unico controllo ed è sicuramente un modo più pythonico per gestire il problema.

```python
#ESEMPIO

if os.path.exists(path):
    file=open(path)
else:
    # do something
################################
try:
    file=open(path)
except OSError:
    # do something
### Conviene sempre usare il secondo metodo con il try except

```

### Traceback

Il traceback è una lista di chiamate a funzione in un punto specifico del codice. I traceback contengono informazioni importanti riguardando l'errore avvenuto che sono cruciali per il debug del codice.

Un traceback andrebbe letto dal basso verso l'alto, l'ultima linea contiene il nome dell'eccezione avvenuta e sopra le varie function call che hanno raisato l'errore in ordine di chiamata

Il contenuto di un traceback può essere mostrato tramite due moduli: **logging** e **traceback**

```python
import logging 
import traceback
import sys
import os

logger=logging.Logger("demo")

#1.
except Exception as e:
    logger.exception(e)
    ##Torna l'usuale messaggio di errore
    
#2.
except Exception as e:
    traceback.print_tb(e.__traceback__,file=sys.stdout)
    ## Torna SOLO il traceback non il tipo di errore (stdot è evitabile, redirige solo l'output che normalmente sarebbe verso stderr)
    
#3.
except Exception as e:
    with opern ("traceback.txt","w") as logfile:
        ## Questo tipo di sintassi solo da python 3.10 alttrimenti molto più complicata, vedi documentazione nel caso
        traceback.print_exception(e)
    os.system('cat traceback.log')
  	#### Salva il log dell'errore e mostra il solito messaggio di errore
```



### Custom exception

Un eccezione può essere sollevata tramite il comando **raise** 

```python
def raising_func():
    raise ExceptionType("Messaggio utile al debug")
 
try:
    raising_func()
except ExceptionType as e:
    print (e)
    
###Ritorna "Messaggio utile al debug" e basta
```

E' possibile creare anche delle eccezioni customizzate creando delle classi che ereditano da una eccezione

```python
class ValueTooLargeError(ValueError):
    def __init__(self, value):
        self.value = value
        super().__init__(f'{self.__class__.__name__}: {self.value} is too large')

value = 100
try:
  if value > 10:
      raise ValueTooLargeError(value)
except ValueError as e:
    print(e)

'''
[Output]
ValueTooLargeError: 100 is too large
'''
##NB il traceback viene stampato solo se il codice crasha. Nel caso di eccezioni da noi create se si vuole mostrare un traceback bisogna usare uno dei due moduli discussi prima
```

### Quando gestire le eccezioni?

Le eccezioni vanno gestite solo quando si ha abbastanza contesto per farlo. Se catturi un errore troppo presto il messaggio di errore sarà totalmente inutile ai fini del debug, i try-except vanno inseriti solo al momento necessario, possibilmente essendo il più possibile specifici 

```python
def parse_line(line):
    """ Parse a line of the file and return the values as float"""
    values = line.strip('\n').split(' ')
    time = float(values[0])
    tension = float(values[1])
    return time, tension

with open('snippets/data/fake_measurements.txt') as lab_data_file:
    for line_number, line in enumerate(lab_data_file): # get the line number
        if not line.startswith('#'): # skip comments
            try:
                time, tension = parse_line(line)
                print(time, tension)
            except ValueError as e:
                print('Line {line_number} error: {e}')
'''
[Output]
##dati
Line 3 error: could non convert string to float: 'pippo'
##dati
'''
```



# Iteratori e iterabili

Un iterabile è un oggetto che ha il metodo \_\_iter\_\_ che ritorna un iteratore.

Un iteratore è un oggetto che implementa un metodo \_\_next\_\_ che dice essenzialmente come scorrere un oggetto

Quando non ci sono più elementi da ritornare un iteratore segnala l'eccezione specifica **StopIteration()**

Un iteratore dispone anche del metodo \_\_iter\_\_ che ritorna l'iteratore stesso. Quindi techincamente un itertore è anche un iterabile però non possiede dati al suo interno

### For loop

Si ha equivalenza tra i due seguenti blocchi di codice

```python
for element in my_list:
    print(element)
#####
#####
list_iterator=iter(my_list)
while True:
    try:
        print(next(list_iterator))
    except StopIteration:
        break
###Ovviamente l'interprete non produce esattamente questo blocco di codice ma in principio sono cose che si assomigliano
```



### Costruzione di un iteratore

Facciamo un esempio e proviamo a costruire un semplice iteratore

```python
class SimpleIterator:
    """ Class implementing a super naive iterator"""
    
    def __init__(self, container):
        self._container = container
        self.index = 0
    
    def __next__(self):
        try:
            # Note: here we are calling the __getitem__ method of self._container
            item = self._container[self.index]
        except IndexError:
            raise StopIteration
        self.index += 1
        return item
    
    def __iter__(self):
        return self
        
class SimpleIterable:
    """ A very basic iterable """
    
    def __init__(self, *elements):
        # We use a list to store elements internally.
        # This provide us with the __getitem__ function
        self._elements = list(elements)
    
    def __iter__(self):
        return SimpleIterator(self._elements)
    
####################################################
from simple_iterator import SimpleIterable
   
my_iterable = SimpleIterable(1., 2., 3., 'stella')
for element in my_iterable:
    print(element)
# Scorre l'iterabile e stampa i singoli elementi
```

E' possibile fare cose più fantasiose tipo creare un iterabile che ogni volta su cui si itera sopra l'ordine di iterazione è casuale, basta cambiare nell'ideratore la gestione dell'indice e usare il modulo random. 

### Funzioni su iteratori

Ci sono diverse funzioni applicabili agli iterabili:

- sum
- all: Ritorna True se tutti gli elementi soddisfano una data condizione
- any: Ritorna True se almeno un elemento soddisfa una data condizione
- max, min
- functool.reduce: Applica una funzione ricorsivamente a una coppia di elementi

## Generatori

Un iterabile occupa un dato spazio in memoria.

Un generatore invece è un oggetto che genera i dati al momento dell'iterazione (approccio **Lazy** (crei qualcosa solo quando ti serve) ) evitando dell'overhead in memoria.

Ci sono diverse funzioni di python che ritornano dei generatori (ad esempio **range**)

#### Generator expression

Si può creare un generatore usando la stessa sintassi delle list comprehension ma con le parentesi tonde 

```python
data=[1,2,3,4]
generatore=(x**2 for x in data)
```

#### Generator function

Il terzo modo per creare generatori è tramite l'uso dell'istruzione **yield** in una funzione. Quando si chiama una funzione generatrice il codice NON viene eseguito ma viene creato un generatore.

Ogni chiamata a next() sul generatore viene eseguito il codice fino all'istruzione **yield**

```python
def generator_function_simple():
    print('First call')
    yield 1
    print('Second call')
    yield 2
    print('I am about to rise a StopIteration exception...')

gen = generator_function_simple() # A generator function returns a generator
print(next(gen)) # We stop at the first yield and get the value
print(next(gen)) # Second yield
next(gen) # The third next() will throw StopIteration

'''
[Output]
First call
1
Second call
2
I am about to rise a StopIteration exception...
Traceback: ********
*****
StopIteration
'''
```

Si può vedere lo yield come una sorta di return del generatore, è esattamente quello che farebbe il metodo next in un iteratore

```python
###Esempio fibonacci
def fibonacci():
    a,b=0,1
    while True:
        yield a
        a,b=b,a+b
        
##NB per iterarci sopra la condizione di stop va aggiunta esternamente oppure passare un parametro alla funzione generatrice e chiamare un break nel while oppure è possibile usare uno strumento di itertools

import itertools 
fib_gen=(fib for fib in itertools.islice(fibonacci(),max_n)) #stoppa l' iterazione a una posizione specifica max_n
```

##### Esempio concreto: LabFileIterator

Creiamo un iteratore che legga dei dati da un file di testo e ignori tutto ciò che non sono i dati (commenti, \n,etc.). Possiamo farlo in due modi: creando un iteratore o creando una funzione generatrice.

_Iteratore_ 

```python
from itertools import dropwhile

class LabFileIterator:
    def __init__(self, file_obj):
        self._lines = dropwhile(lambda line: line.startswith('#'), file_obj)
        
    def __next__(self):
        line = next(self._lines)
        values = line.strip('\n').split(' ')
        time = float(values[0])
        tension = float(values[1])
        return time, tension
    
    def __iter__(self):
        return self

with open('snippets/data/fake_measurements.txt') as lab_data_file:
    try:
        for line_number, (time, tension) in enumerate(LabFileIterator(lab_data_file)):
            print(line_number, time, tension)
    except ValueError as e:
        # Here we get the wrong line number! Why?
        print('Line {} error: {}'.format(line_number, e))
```

_Funzione Generatrice_

```python
class LabFile:
    def __init__(self, file_obj):
        self._file = file_obj
       
    def __iter__(self):
        # This is more readible
        for i, line in enumerate(self._file):
            if line.startswith('#'):
                continue
                ### continue passa al passo del ciclo successivo
            values = line.strip('\n').split(' ')
            try:
                time = float(values[0])
                tension = float(values[1])
            except ValueError as e:
                print('Line {} error: {}'.format(i, e))
                continue
            yield time, tension

with open('snippets/data/fake_measurements.txt') as lab_data_file:
    for time, tension in LabFile(lab_data_file):
        print(time, tension)
        
'''
[Output]
##dati
Line 3 error: could non convert string to float: 'pippo'
##dati
'''
```



#### Funzioni generatrici built-in

Le sequenti funzioni built-in ritornano dei GENERATORI

- enumerate: ritorna coppia indice, iterabile

- map: Apllica una funzione a un elemento

- filter: Ritorna solo gli elementi che soddisfano una funzioni

- zip: Ritorna coppie di elementi

- reverse: Loop in ordie contrario

- **Itertools**:

  - islice:	Loop con uno start, stop e step

  - takewhile: Ferma il loop quando una condizione diventa falsa

  - accumulate:  Applica una funzione iterativamente a una coppia di elementi (es. list(accumulate[1,2,3,4],func.operator.mul) ritorna [1!,2!,3!,4!] )

  - chain: Concatena due sequenze

  - cycle: Looppa su una sequenza in modo ciclico all'infinito

  - permutations: Crea tutte le permutazioni di una data lunghezza sotto forma di tuple

  - product: Crea il prodotto cartesiano tra due sequenze 

  - groupby:  Raggruppa iterabili per una data condizione (si aspetta che l'iterabile sia ordinato rispetto quella condizione)

    ```python
    l3=[1,2,3,4,5,6]
    def is_even(n):
        return n%2==0
    l3.sort(key=is_even)
    for k,g in groupby(l3,key=is_even):
        print (k,list(g))
        
    '''
    [Output]
    False [1,3,5]
    True [2,4,6]
    '''
    ```

    

  - ... etc

# Lambda Functions

E' possibile definire delle funzioni anonime senza nome. Questa feature è ereditata dalla programmazione funzionale

```python
### Le seguenti sintassi sono equivalenti
def multiply(a,b):
    return a*b

multiply=lambda a,b: a*b
```

